### ISSUE TITLE
Boundary Condition for ROMS grid using GODAS data

### ISSUE THREAD

**Issue by prasannakanti** [sameerCoder/IC_BC_Godas_to_ROMS#1]
Hi @sameerCoder 
 I got this error while creation boundary condition for the ROMS grid.
Traceback (most recent call last):
File "/home/prasanna/miniconda/envs/xesmf_env/lib/python3.7/multiprocessing/pool.py", line 121, in worker
result = (True, func(*args, **kwds))
File "/home/prasanna/miniconda/envs/xesmf_env/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
return list(map(*args))
File "withcomment_Boundary_condition_genertion_from_Godas_to_ROMS.py", line 65, in do_file
zeta = remap_bdry(file, 'SSH', src_grd, dst_grd, dst_dir=dst_dir)
File "/home/prasanna/MOM6/GodasToROMS_BC/remap_bdry.py", line 43, in remap_bdry
src_var = cdf.variables[src_varname]
KeyError: 'SSH'

I think you can help me . Kindly help me a little.

**Comment by prasannakanti** [comment]
Hi, @sameerCoder , 
I have created the boundary files. But I cannot see the data in ferret. 
es? us Godas_day_27_bdry_GODASROMSBC.nc
           *** NOTE:
           *** NOTE: Could not adjust grid for variable h
 **ERROR: inconsistent data grids: File needs axis attributes on coordinate variables indicating correct directions
How to resolve this error. Please help me a bit.
